version: "3.8"
services:
  # elastic search cluster?
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    ports:
      - 9200:9200
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      - xpack.security.transport.ssl.enabled=false
      - discovery.type=single-node
      - ELASTIC_PASSWORD=adminadmin
  #seaweedfs cluster (master, volume, filer)
  master:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 127.0.0.1:9333:9333
      - 127.0.0.1:19333:19333
      - 127.0.0.1:9324:9324
    command: 'master -ip=master -ip.bind=0.0.0.0'
    volumes:
      - seaweed-master:/data
  volume:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:18080:18080
      - 127.0.0.1:9325:9325
    command: 'volume -mserver="master:9333" -ip.bind=0.0.0.0 -port=8080 -dir="/data"'
    depends_on:
      - master
    volumes:
      - seaweed-volume:/data
  filer:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 127.0.0.1:8888:8888
      - 127.0.0.1:18888:18888
      - 127.0.0.1:9326:9326
    command: 'filer -master="master:9333" -ip.bind=0.0.0.0'
    tty: true
    stdin_open: true
    depends_on:
      - master
    volumes:
      - seaweed-filer:/data
  s3:
    restart: always
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 127.0.0.1:8333:8333
    command: 's3 -filer="filer:8888" -ip.bind=0.0.0.0 -config=/config/config.json'
    depends_on:
      - master
      - filer
    volumes:
      - seaweed-s3:/data
      - ./s3-config.json:/config/config.json
  # ingestion API
  gnam-api:
    image: ghcr.io/fcl-lm/gnam-api:main
    container_name: gnam-api
    ports:
        - "9090:9090"
    environment:
        S3_ENDPOINT: http://s3:8333    # seaweedfs s3 endpoint
        AWS_ACCESS_KEY_ID: adminadmin
        AWS_SECRET_ACCESS_KEY: adminadmin
    volumes:
        - source_document:/data
  # interaction API
  privategpt:
    image: ghcr.io/fcl-lm/privategpt:main
    ports:
      - 5000:5000
    environment:
      S3_ENDPOINT: "http://s3:8333"
      S3_ACCESS_KEY: "adminadmin"
      S3_SECRET_KEY: "adminadmin"
      ELASTIC_ENDPOINT: "http://elastic:adminadmin@elastic:9200"
      ELASTIC_INDEX: test_index
      MODEL_TYPE: GPT4All
      MODEL_NAME: ggml-gpt4all-j-v1.3-groovy.bin
      EMBEDDINGS_MODEL_NAME: all-MiniLM-L6-v2
      MODEL_N_CTX: 10000
      MODEL_N_BATCH: 8
      TARGET_SOURCE_CHUNKS: 4
    volumes:
      - privategpt-tmp:/tmp
      - privategpt-models:/privategpt/models
  # updating the vector embeddings for the documents to be ingested with the gnam-api periodically
  vector-store-updater:
    image: ghcr.io/fcl-lm/vector-store-updater:main
    environment:
        ELASTIC_ENDPOINT: http://elastic:adminadmin@127.0.0.1:9200
        ELASTIC_INDEX: test_index
        EMBEDDINGS_MODEL_NAME: all-MiniLM-L6-v2
        S3_ENDPOINT: "http://127.0.0.1:8333"
        S3_ACCESS_KEY: "adminadmin"
        S3_SECRET_KEY: "adminadmin"
    volumes:
      - vector-store-updater:/root/ntlk_data


volumes:
  source_document:
  privategpt-tmp:
  privategpt-models:
  seaweed-master:
  seaweed-volume:
  seaweed-filer:
  seaweed-s3:
  elastic:
  vector-store-updater: