apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-config
data:
  config.json: |
    {
    "identities": [
        {
            "name": "me",
            "credentials": [
                {
                "accessKey": "adminadmin",
                "secretKey": "adminadmin"
                }
            ],
            "actions": [
                "Read",
                "Write",
                "List",
                "Tagging",
                "Admin"
            ]
        }
    ]
    }