apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      initContainers:
        - name: sysctl
          image: busybox
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      containers:
        - name: elastic
          image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9200
          resources:
            limits:
              cpu: "2"
              memory: 10Gi
            requests:
              cpu: "1"
              memory: 5Gi
          volumeMounts:
            - name: elastic-data
              mountPath: /usr/share/elasticsearch/data
          env:
            - name: xpack.security.enabled
              value: "false"
            - name: discovery.type
              value: single-node
            - name: ELASTIC_PASSWORD
              value: adminadmin
      volumes:
        - name: elastic-data
          persistentVolumeClaim:
            claimName: elastic-search-persistent