apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnam-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gnam-api
  template:
    metadata:
      labels:
        app: gnam-api
    spec:
      #init container to wait for s3 to be ready (IP and DNS resolution)
      initContainers:
        - name: wait-for-s3
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nslookup seaweedfs-s3.default.svc.cluster.local; do echo waiting for s3; sleep 2; done;']
      containers:
        - name: gnam-api
          image: ghcr.io/fcl-lm/gnam-api:main
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 2Gi
          env:
            - name: S3_ENDPOINT
              value: http://seaweedfs-s3:8333
            - name: AWS_ACCESS_KEY_ID
              value: adminadmin
            - name: AWS_SECRET_ACCESS_KEY
              value: adminadmin
          volumeMounts:
            - name: source-document
              mountPath: /data
      volumes:
        - name: source-document
          persistentVolumeClaim:
            claimName: gnam-api-persistent