apiVersion: v1
kind: Service
metadata:
  name: privategpt-loadbalancer-service
spec:
  selector:
    app: privategpt
  ports:
    - protocol: TCP
      port: 80   #port exposed by the service
      targetPort: 5000  #port exposed by the pods, directs traffic to this port of the pods
  type: LoadBalancer