apiVersion: apps/v1
kind: Deployment
metadata:
  name: privategpt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: privategpt
  template:
    metadata:
      labels:
        app: privategpt
    spec:
      initContainers:
        # wait for elastic and s3 to be ready
        # - name: wait-for-elastic
        #   image: busybox
        #   command: ['sh', '-c', 'until wget -qO- http://elastic:9200; do echo waiting for elastic; sleep 2; done;']
        - name: wait-for-elastic
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', "until nslookup elastic.default.svc.cluster.local; do echo waiting for elastic-search; sleep 2; done"]      
        # - name: wait-for-s3
        #   image: busybox
        #   command: ['sh', '-c', 'until wget -qO- http://s3:8333; do echo waiting for s3; sleep 2; done;']
        - name: wait-for-s3
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', "until nslookup seaweedfs-s3.default.svc.cluster.local; do echo waiting for s3-service; sleep 2; done"]      
        
      containers:
        - name: privategpt
          # image: privategpt-localbuild:latest
          # imagePullPolicy: Never
          image: ghcr.io/fcl-lm/privategpt:main
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "11"
              memory: 15Gi
            requests:
              cpu: "10"
              memory: 10Gi
          env:
            - name: S3_ENDPOINT
              value: "http://seaweedfs-s3:8333"
            - name: S3_ACCESS_KEY
              value: "adminadmin"
            - name: S3_SECRET_KEY
              value: "adminadmin"
            - name: ELASTIC_ENDPOINT
              value: "http://elastic:adminadmin@elastic:9200"
            - name: ELASTIC_INDEX
              value: test_index
            - name: MODEL_TYPE
              value: GPT4All
            - name: MODEL_NAME
              value: ggml-gpt4all-j-v1.3-groovy.bin
            - name: EMBEDDINGS_MODEL_NAME
              value: all-MiniLM-L6-v2
            - name: MODEL_N_CTX
              value: "10000"
            - name: MODEL_N_BATCH
              value: "8"
            - name: TARGET_SOURCE_CHUNKS
              value: "4"
          volumeMounts:
            - name: privategpt-tmp
              mountPath: /tmp
            - name: privategpt-models
              mountPath: /privategpt/models
      volumes:
        - name: privategpt-tmp
          emptyDir: {}
        - name: privategpt-models
          emptyDir: {}