apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - name: master
          image: chrislusf/seaweedfs
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9333
            - containerPort: 19333
            - containerPort: 9324
          resources:
            limits:
              cpu: "2"
              memory: 10Gi
            requests:
              cpu: "0.5"
              memory: 2Gi
          command: ["/usr/bin/weed" , "master", "-ip=seaweedfs-master", "-ip.bind=0.0.0.0", "-mdir=/data"]
          volumeMounts:
            - name: seaweed-master-data
              mountPath: /data

      volumes:
        - name: seaweed-master-data
          persistentVolumeClaim:
            claimName: seaweedfs-master-persistent
