apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: volume
  template:
    metadata:
      labels:
        app: volume
    spec:
      containers:
        - name: volume
          image: chrislusf/seaweedfs
          imagePullPolicy: IfNotPresent
          tty: true
          stdin: true
          ports:
            - containerPort: 8080
            - containerPort: 18080
            - containerPort: 19333
            - containerPort: 9325
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "0.5"
              memory: 2Gi
          command: ["/usr/bin/weed" ,"volume", "-mserver=seaweedfs-master:9333", "-max=0","-ip.bind=0.0.0.0", "-port=8080", "-dir=/data"]
          volumeMounts:
            - name: seaweed-volume-data
              mountPath: /data
      volumes:
        - name: seaweed-volume-data
          persistentVolumeClaim:
            claimName: seaweedfs-volume-persistent