apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-store-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vector-store-updater
  template:
    metadata:
      labels:
        app: vector-store-updater
    spec:
      initContainers:
        # wait for elastic and s3 to be ready
        - name: wait-for-elastic
          image: busybox
          command: ['sh', '-c', 'until wget -qO- http://elastic-search:9200; do echo waiting for elastic; sleep 2; done;']
        - name: wait-for-s3
          image: busybox
          command: ['sh', '-c', 'until wget -qO- http://seaweedfs-s3:8333; do echo waiting for s3; sleep 2; done;']
      containers:
        - name: vector-store-updater
          image: ghcr.io/fcl-lm/vector-store-updater:main
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "0.5"
              memory: 2Gi
          env:
            - name: ELASTIC_ENDPOINT
              value: http://elastic:adminadmin@elastic-search:9200
            - name: ELASTIC_INDEX
              value: test_index
            - name: EMBEDDINGS_MODEL_NAME
              value: all-MiniLM-L6-v2
            - name: S3_ENDPOINT
              value: "http://seaweedfs-s3:8333"
            - name: S3_ACCESS_KEY
              value: "adminadmin"
            - name: S3_SECRET_KEY
              value: "adminadmin"
          volumeMounts:
            - name: vector-store-updater-data
              mountPath: /root/ntlk_data
      volumes:
        - name: vector-store-updater-data
          emptyDir: {}