apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-gui
  template:
    metadata:
      labels:
        app: web-gui
    spec:
      initContainers:
        # wait for flask to be ready (with the load balancer service)
        - name: wait-for-flask
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nslookup privategpt-loadbalancer-service; do echo waiting for flask; sleep 2; done;']
      containers:
        - name: web-gui
          image: ghcr.io/fcl-lm/fcl-svelte-webgui:main
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 2Gi
          env:
            - name: PUBLIC_FLASK_ENDPOINT
              value: http://privategpt-loadbalancer-service:5000   #using the loadbalancer service, also the loadbalancer service IP should be public
          volumeMounts:
            - name: source-document
              mountPath: /data
      volumes:
        - name: source-document
          emptyDir: {}